### ISSUE TITLE
smooch__WEBPACK_IMPORTED_MODULE_1___default(...)....  is not a function

### ISSUE THREAD

**Issue by FeLauton** [zendesk/sunshine-conversations-web#709]
**bug report**

**smooch__WEBPACK_IMPORTED_MODULE_1___default(...).init is not a function
TypeError: smooch__WEBPACK_IMPORTED_MODULE_1___default(...).init is not a function
    at initializeSmooch (http://localhost:3000/static/js/bundle.js:111696:64)
    at SmoochWebChat (http://localhost:3000/static/js/bundle.js:111709:11)
    at RouterWrapper (http://localhost:3000/static/js/bundle.js:110374:115)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:275914:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:279885:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:281188:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:286147:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:285417:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:285340:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:285313:11)**

-   Delivery method: [ npm ]
-   Version ( 5.6.2 ):
-   Browser: [ all ]
-   OS: [ Windows 11 ]

**Comment by kaiwa** [comment]
:+1:

**Comment by klimeryk** [comment]
Same here, trying the most basic usage of the widget and I was scratching my head what I was doing wrong. Thanks for reporting it and restoring my sanity 😅 

For reference, I was just trying the most basic setup:
```
import Smooch from 'smooch';

...
Smooch.init( { integrationId: '...' } );
```

Forcing version 5.6.0 indeed makes it work as expected - thanks for the hint, @kaiwa! 🙇

**Comment by LucasBourgeois** [comment]
It seems that it's because since 5.6.2, there is no longer a module.exports= in the lib/index.js..

**Comment by kytta** [comment]
Yep, the export is empty:

```ts
import Smooch from 'smooch';

// I've also tried
// import * as Smooch from 'smooch';

console.log(Smooch)
```

logs an empty object (`{}`)

**Comment by kytta** [comment]
Let me get impertinent and tag @DataWearsAHood and @mspensieri, as they seem to have been the last people acting on issues here. Could you or your colleagues look into this? It makes new versions of Smooch unusable with Node :(

**Comment by mspensieri** [comment]
Hello 👋 thanks for the ping . As you've noticed, we don't actively monitor this repo for bug reports. In the future you'd get more prompt support by using the support widget in our help center https://support.zendesk.com/hc/en-us/ or from Admin Center > Get More Help.

For now I've forwarded this report to the team that maintains the web messenger, and they've filed a bug for this issue

**Comment by kytta** [comment]
For all interested: The `default` export seems to be back in Smooch v5.7.3. I have not verified whether it works yet

<img width="741" alt="Image" src="https://github.com/user-attachments/assets/f3cd180b-3aca-44e0-93be-cac7326cbe01" />

**Comment by urszulafratczak** [comment]
Exactly, it's fixed in version 5.7.3. Sorry for delayed update 🙏
